language: node_js
node_js:
- 6
- 5
- 4
script:
- npm run lint
- npm run nsp
branches:
  only:
  - master
deploy:
  provider: npm
  email: billing.media@schibsted.media
  on:
    branch: master
    node: '6'
  api_key:
    secure: X+xwDXmqgSPzYXTSDXBjJgtYbNES/gTD5qWwaYcwz3kviMYXCfMvulI179Yt+6EB57ERm4AGHF4a4+SCAjYTNtqq29eNXF34hmgT6/JnBN6dN+/CefTdNQr9xwPcsSjKMzkWReNzc2v4CMuX8wgjmgzfWNLn0DHTT+9B0sev8QTl+85dpM9ZaDgypr7XXD0PRj3eGyQevVEdyVRuGsu0tVXPLyIc3o9wvmcLUFpIomHDtNgPXYnLzIzhrpdzHOzZwOXOJm9+aGylK5ZDWdZ2dTtB04396Wlhtw+VU6RBy/d009FTl6HHF+M43f4ftkybb0KrPkvo1dru+itx/LHCNbh1RrtLw+1l+sALn8PpzRrcYfzMd/Lk11Qu2gucNFGnN4fPrO2uMiW/AtPYQzDgFuAuggnjvkhWpvBDLmMj1PPxocBpB3/deRA9koJlDQDob3PpAFzkkHEztARryVp7xMdPxh/Bo2xeGNit7wEchGWpJfJOn/uCB9+I6TOGMBpnpfjPwgd7M86Q0ea/aeL6rYINCXOCT1ihwwv/nz8U/5wX2AWVkg5IZxVFrAUYJBxC5zqJerBFkBtQyBV2yBpKfxpCr91BWn+Q5ZV9NkHVG6xhGpDu3Mn+xI8wr+qT/BfzhnhCB/LCtu/r8lr6Y3bztIolSOEqMN4djY9aIkLXFhc=
